---
  swagger: "2.0"
  info:
    title: "twitter-clone"
    description: "Twitter Clone"
    version: "1.0-SNAPSHOT"
  schemes:
    - "http"
  consumes:
    - application/json
  produces:
    - application/json
